# -*- coding: utf-8 -*-
"""tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/sithu31296/semantic-segmentation/blob/main/notebooks/tutorial.ipynb

## Setup
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/sithu31296/semantic-segmentation
# %cd semantic-segmentation
# %pip install -e .

import torch
from torchvision import io
from torchvision import transforms as T
from PIL import Image

def show_image(image):
    if image.shape[2] != 3: image = image.permute(1, 2, 0)
    image = Image.fromarray(image.numpy())
    return image

"""## Show Available Pretrained Models"""

from semseg import show_models

show_models()

"""## Load a Pretrained Model

Download a pretrained model's weights from the result table (ADE20K, CityScapes, ...) and put it in `checkpoints/pretrained/model_name/`.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U gdown

import gdown
from pathlib import Path

ckpt = Path('./checkpoints/pretrained/segformer')
ckpt.mkdir(exist_ok=True, parents=True)

url = 'https://drive.google.com/uc?id=1-OmW3xRD3WAbJTzktPC-VMOF5WMsN8XT'
output = './checkpoints/pretrained/segformer/segformer.b3.ade.pth'

gdown.download(url, output, quiet=False)

from semseg.models import *

model = eval('SegFormer')(
    backbone='MiT-B3',
    num_classes=150
)

try:
    model.load_state_dict(torch.load('checkpoints/pretrained/segformer/segformer.b3.ade.pth', map_location='cpu'))
except:
    print("Download a pretrained model's weights from the result table.")
model.eval()

print('Loaded Model')

"""## Simple Image Inference

### Load Image
"""

image_path = './assests/ade/ADE_val_00000049.jpg'
image = io.read_image(image_path)
print(image.shape)
show_image(image)

"""### Preprocess"""

# resize
image = T.CenterCrop((512, 512))(image)
# scale to [0.0, 1.0]
image = image.float() / 255
# normalize
image = T.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))(image)
# add batch size
image = image.unsqueeze(0)
image.shape

"""### Model Forward"""

with torch.inference_mode():
    seg = model(image)
seg.shape

"""### Postprocess"""

seg = seg.softmax(1).argmax(1).to(int)
seg.unique()

from semseg.datasets import *

palette = eval('ADE20K').PALETTE

seg_map = palette[seg].squeeze().to(torch.uint8)
show_image(seg_map)

"""## Show Available Backbones"""

from semseg import show_backbones

show_backbones()

"""## Show Available Heads"""

from semseg import show_heads

show_heads()

"""## Show Available Datasets"""

from semseg import show_datasets

show_datasets()

"""## Construct a Custom Model

### Choose a Backbone
"""

from semseg.models.backbones import ResNet

backbone = ResNet('18')

# init random input batch
x = torch.randn(2, 3, 224, 224)

# get features from the backbone
features = backbone(x)
for out in features:
    print(out.shape)

"""### Choose a Head"""

from semseg.models.heads import UPerHead

head = UPerHead(backbone.channels, 128, num_classes=10)

seg = head(features)
seg.shape

from torch.nn import functional as F
# upsample the output
seg = F.interpolate(seg, size=x.shape[-2:], mode='bilinear', align_corners=False)
seg.shape

"""Check `semseg/models/custom_cnn.py` and `semseg/models/custom_vit.py` for a complete construction for custom model."""

